### PR TITLE
Master

### PR DESCRIPTION
**Pull request by feathered-arch**
This looks like a bit of a mess, but please reference the last two commits (binaries+code). I'd be curious to know if you find the AVX2 version of this plugin to be faster. Please feel free to let the Vray ppl know about this. I don't have Vray to test this plugin with it, btw.

It fixes some serious issues. 

Note, I've made a parallel pull request with Bercon -- I'm making one with you because the last time you undid a fix when your pull request overwrote mine :) So hopefully we can avoid a bug fix conflict again in the future. 

I'm not fully understanding github, I don't think, so apologies if I'm doing this wrong.

### CODE REVIEW

**Comment by yavor-rubenov** [comment]
First of all sorry about the mixup with the pull request - I'm quite new to github too.
Secondly - I'll be quite busy till the end of May so I can't really check what's going on and do tests.
Some quick notes:

- AVX2 - this one will need some testing to see if it brings benefits. The problem with AVX2 and recent Intel CPUs is that they go to lower clocks when processing those instructions. So if there are very few of them mixed with non AVX code - the end result might even be slower code. 

- About Numrefs and Numsubs - I think they are still needed (http://help.autodesk.com/view/3DSMAX/2020/ENU/?guid=__cpp_ref_class_animatable_html). When they are commented you just inherit the ones from Animatable that just return 0. With those returning 0 Max will no longer see those refs and sub anims - this will avoid the crash but will also probably break saving and loading. Another thing that might happen with Numrefs returning 0 is that Max won't know that the bercon tex has a link to some other texture and might decide to delete that other texture..

- Changes to BerconSC.h : There seems to be quite a few V-Ray users on Maxes before 2017 so ideally there should be support for those. If you don't have the required SDKs - leave it as is and I can add the required #ifdefs here and there. About the override thing - ideally all inherited methods in BerconSC should have the override keyword - with it if something changes in the base class ShadeContext in some newer Max version - there will be an error when compiling. If there's only the virtual keyword - there will be no error the method will no longer override the one in ShadeContext.

**Comment by feathered-arch** [comment]
>
>    -
>
>    AVX2 - this one will need some testing to see if it brings benefits.
>    The problem with AVX2 and recent Intel CPUs is that they go to lower clocks
>    when processing those instructions. So if there are very few of them mixed
>    with non AVX code - the end result might even be slower code.
>
>  I will test. I've asked Grant Warwick for a file (he loves BerconMaps) to
test with. If you have one please feel free to send one. At some point I
will download a Vray trial and test with that.

>
>    -
>
>    About Numrefs and Numsubs - I think they are still needed (
>    http://help.autodesk.com/view/3DSMAX/2020/ENU/?guid=__cpp_ref_class_animatable_html).
>    When they are commented you just inherit the ones from Animatable that just
>    return 0. With those returning 0 Max will no longer see those refs and sub
>    anims - this will avoid the crash but will also probably break saving and
>    loading. Another thing that might happen with Numrefs returning 0 is that
>    Max won't know that the bercon tex has a link to some other texture and
>    might decide to delete that other texture..
>
> Thank you for that! I think this method is valid. I have tested it on
2020, 2019 and 2016, and I haven't experienced any problems with animations
disappearing although the test file I used was not exactly heavy-duty. But
it appears to work. My last SDK is for 2016 so I'm not sure when Max got
intelligent about this, but it seems to provide a public way of simply
calling NumRefs without having to provide any input. It seems to prefer
this. I'm mystified as to what broke between 2016 and 2017 -- it must be
something Autodesk hasn't fully documented, and is internal and behind
their SDK.

         int NumSubs() { return 1; }; // Always return 1 when
ParameterBlocks are used
Animatable* SubAnim(int i);
TSTR SubAnimName(int i);

int NumRefs() // Max will handle this internally. I can confirm this method
works as far back as 2016. MtlLib.h (2017+) and imtl.h (<=2016) process
this internally.
{ // Refer to line 103 of Materials\MtlLib.h
int count = 0;
return count;
}

>
>    -
>
>    Changes to BerconSC.h : There seems to be quite a few V-Ray users on
>    Maxes before 2017 so ideally there should be support for those. If you
>    don't have the required SDKs - leave it as is and I can add the required
>    #ifdefs here and there. About the override thing - ideally all inherited
>    methods in BerconSC should have the override keyword - with it if something
>    changes in the base class ShadeContext in some newer Max version - there
>    will be an error when compiling. If there's only the virtual keyword -
>    there will be no error the method will no longer override the one in
>    ShadeContext.
>
> I appreciate that you're busy with your full-time job, and I thank you so
very much for responding! I'm pursuing this on my end solely as a hobby
(not being paid by anyone), and am not a programmer by training. I will try
to be mindful of your time, and won't bother you too much. I am SO SO
grateful for your response and insight.

Thanks again!

--James in NYC

**Comment by feathered-arch** [comment]
I take the bottom part back. Testing shows that with that method
(obviously) it is not saving changes to the scene.
My bad.

-James
347.866.5522 (vm/sms)




---------- Forwarded message ---------
From: James Stewart <james@jkstewart.com>

 I think this method is valid. I have tested it on 2020, 2019 and 2016, and
I haven't experienced any problems with animations disappearing although
the test file I used was not exactly heavy-duty. But it appears to work. My
last SDK is for 2016 so I'm not sure when Max got intelligent about this,
but it seems to provide a public way of simply calling NumRefs without
having to provide any input. It seems to prefer this. I'm mystified as to
what broke between 2016 and 2017 -- it must be something Autodesk hasn't
fully documented, and is internal and behind their SDK.

         int NumSubs() { return 1; }; // Always return 1 when
ParameterBlocks are used
Animatable* SubAnim(int i);
TSTR SubAnimName(int i);

int NumRefs() // Max will handle this internally. I can confirm this method
works as far back as 2016. MtlLib.h (2017+) and imtl.h (<=2016) process
this internally.
{ // Refer to line 103 of Materials\MtlLib.h
int count = 0;
return count;
}

**Comment by yavor-rubenov** [comment]
@kentebird I've pushed a new branch (code changes in https://github.com/yavor-rubenov/BerconMaps/commit/b688fabf523d30ecc2a6ee7af4070c8292edf5bd) that I think fixes the crashes on save. I've included your change about the noise size spinner. 
If you can take a look..

**Comment by feathered-arch** [comment]
That works.

You are a god among men!

-James
347.866.5522 (vm/sms)

**Pull request closed without merging**
